// Generated by CoffeeScript 1.6.3
(function() {
  var ANIMATE_HTML_SUFFIX, copyToGenFromRoot, executeTask, fs, loadAndExec, mkdirp, path, phantom, scrapeAnimate;

  phantom = require('phantom');

  path = require('path');

  fs = require('fs.extra');

  mkdirp = require('mkdirp');

  ANIMATE_HTML_SUFFIX = '_edgeActions.html';

  /* Example
  require 'genanimate'
  config =
    animate_dir: 'assets/edge_animate'
    src: ['test']
    dist: 'gen'
    html_path: 'gen'
    images_path: 'gen/images'
  executeTask config
  */


  loadAndExec = function(url, execCode, callback) {
    return phantom.create(function(ph) {
      return ph.createPage(function(page) {
        return page.open(url, function(status) {
          return setTimeout((function() {
            return page.evaluate(execCode, function(result) {
              return callback(ph, result);
            });
          }), 100);
        });
      });
    });
  };

  copyToGenFromRoot = function(config, callback) {
    var from, to;
    console.log(config.animate_dir);
    from = path.join(path.resolve(config.animate_dir), 'images');
    to = path.join(path.resolve('.'), config.images_path);
    return console.log(from, to);
  };

  scrapeAnimate = function(config, target, callback) {
    var animate_target;
    animate_target = 'file://' + path.join(path.resolve(config.animate_dir), "" + target + "_edgeActions.html");
    return loadAndExec(animate_target, (function() {
      return $('#Stage').html();
    }), function(ph, result) {
      var to;
      ph.exit();
      to = path.join(path.resolve(config.dist), config.html_path + '.html');
      fs.writeFileSync(to, result);
      return callback(result);
    });
  };

  executeTask = function(config, callback) {
    var _ref;
    copyToGenFromRoot(config);
    config.src = ((_ref = config.src) != null ? _ref.length : void 0) ? config.src : [config.src];
    return config.src.forEach(function(s) {
      return scrapeAnimate(config, s, function(result) {
        return console.log(result);
      });
    });
  };

  exports.genanimate;

  module.exports = {
    genanimate: executeTask
  };

}).call(this);
